### ISSUE TITLE
Esbonio doesn't work when conf.py not in source directory

### ISSUE THREAD

**Issue by AkibAzmain** [swyddfa/esbonio#142]
I'm using the Esbonio VSCode extension (version 0.5.1). It works very well. But if I move conf.py to some other place, the language server fails.

I'm using Sphinx 3.4.3 with GNU Autotools. I have a template file named ``conf.py.in``, from which ``conf.py`` is generated by the ``configure`` script (you should be familiar be this if you compile software from source code).

I tried to find a setting with changes Sphinx arguments but found none.

Sphinx: 3.4.3
Esbonio: 0.5.1
Autoconf: 2.59

**Comment by alcarney** [comment]
The language server does assume that your `*.rst` files are in the same directory as `conf.py`, something that's currently [hard coded](https://github.com/swyddfa/esbonio/blob/72fbbf383f410294e5b513e5e08b8594756da6ce/lib/esbonio/esbonio/lsp/sphinx.py#L196) into the initialisation code. I imagine a fix for this will also flush out a way to resolve #62.... 

Is this something you want to have a go at fixing? (#143 made it sound like you might), if so could you assign the issue to yourself so that I know to focus on something else :)

**Comment by alcarney** [comment]
v0.6.0 of both the Language Server and the VSCode extension was just released which will now let you override the default `srcdir` Sphinx is configured with. You can set the `esbonio.sphinx.srcDir` option to either 
- `/an/absolute/path/to/your/srcdir`
- `${confDir}/../srcdir` - a path relative to the folder containing your `conf.py`
- `${workspaceRoot}/your/srcdir` - a path relative to the workspace root.

Hopefully that resolves your issue but feel free to reopen this if it doesn't!
