### ISSUE TITLE
Change the pinned Pip version

### ISSUE THREAD

**Issue by twodrops** [swyddfa/esbonio#347]
esbonio expects a latest version of Pip to be installed and seems to be pinning it as minimum version. Looks like this is one of the updated versions available in PyPi and not a pip that is distributed with a Linux distribution like Ubuntu 20.04.

Can the minimum expected version to be set as the one which is distributed with Ubuntu 20.04. I guess this is pip 20.0.2.

**Comment by alcarney** [comment]
> esbonio expects a latest version of Pip to be installed and seems to be pinning it as minimum version

Do you happen to know where this pin is coming from? 

I could be wrong but I don't see anything in the [setup.cfg](https://github.com/swyddfa/esbonio/blob/release/lib/esbonio/setup.cfg) that affects the pip version. There is a minimum version for setuptools in the [pyproject.toml](https://github.com/swyddfa/esbonio/blob/release/lib/esbonio/pyproject.toml#L2) but since that version came out in 2017 I'm going to assume it would affect pip either...

@lextm is the vscode-restructuredtext extension pinning the pip version at all?

**Comment by lextm** [comment]
Duplicate to https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/373

**Comment by twodrops** [comment]
This works fine with rest Extension 184.0.0. Thanks for checking this.
