### ISSUE TITLE
Search conf.py from bottom to top

### ISSUE THREAD

**Issue by stsewd** [swyddfa/esbonio#415]
Hi, thanks for creating this!

When searching the conf.py file, currently esbonio starts looking from the root of the project, but often big projects may have separate set of docs on the same project, or a project could have several sphinx projects as test data, or even a file named conf.py somewhere in their code, this leads to esbonio using the wrong conf.py file for a given rst file.

Another approach to look for the conf.py file given a rst file would be from bottom to top, which I think will give more accurate results, as the conf.py file usually is the root of the source directory (also true for sphinx projects that user the `docs/source` structure).

I'm not that familiar with the internals of LSP, so not sure if this is possible or if it goes against the "rules".

**Comment by alcarney** [comment]
I'm sure it is possible, just not something that has been implemented yet :smile: 

Currently the language server only supports a single Sphinx project, mostly due to Sphinx/docutils relying on a certain amount of global state. I have a few ideas for how support for multiple projects may be added, but right now I'm focusing on making it work well for a single project.

>  this leads to esbonio using the wrong conf.py file for a given rst file.

The server does provide options (like [`esbonio.sphinx.confDir`](https://swyddfa.github.io/esbonio/docs/stable/en/lsp/getting-started.html#confval-sphinx.confDir-string)) that allow you to override the default discovery mechanism if it's finding the wrong `conf.py`. However, it's probably not that useful if you're trying to work on multiple projects at once.

> Another approach to look for the conf.py file given a rst file would be from bottom to top,

If I'm understanding what you mean by "bottom to top" correctly then I really like this idea! I can imagine that when support for multiple projects comes along, Sphinx applications could be lazily created on demand using the `conf.py` that's found by traversing up the directory tree from the current rst file.

> thanks for creating this!

Thanks for taking an interest in this! :smile:

**Comment by lextm** [comment]
vscode-restructuredtext extension scans the working directory to locate all `conf.py` files, and allows users to choose which one should be used for live preview/LSP,

https://docs.restructuredtext.net/articles/preview#preview-mode-selection

**Comment by alcarney** [comment]
This is now [implemented](https://github.com/swyddfa/esbonio/blob/79769b1caa2c19a045f1c9ab4360b5b12cbb7c05/lib/esbonio/esbonio/server/features/sphinx_manager/config.py#L229) as part of the upcoming v1 of the server
