### ISSUE TITLE
Update check prevents server from starting

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#454]
In cases where there is limited to no internet connectivity, the update check mechanism in the VSCode extension can prevent the existing version of the language server from ever starting.

```
[client] Fetching latest version from PyPi
[client] Unable to fetch version from PyPi getaddrinfo EAI_AGAIN pypi.org
```
**Note:** It is possible to work around this by setting `esbonio.server.updateFrequency` to `never`

**Comment by lextm** [comment]
Not able to connect to public PyPI (or overall the internet) is very common in enterprises. Some companies even have their own special Python setup you cannot find elsewhere.

Thus, I think an enterprise friendly extension should only verify

* If the dependencies are installed or not.
* If a dependency installed is older than a baseline version.

Then, it can decide whether to continue initialization, or show a prompt to warn the user that certain features will not be available due to missing/out-of-date dependencies.

Auto-update should be optional and off by default.
