### ISSUE TITLE
CI isn't testing Sphinx 5.x on Python 3.7

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#463]
It appears that CI isn't actually testing against Sphinx 5.x when running under Python 3.7, even though it's explicitly requested in the [tox env](https://github.com/swyddfa/esbonio/blob/develop/lib/esbonio/pyproject.toml#L78) definition.

```
py37-sphinx4 installed: ...,Sphinx==4.3.2,...
py37-sphinx5 installed: ...,Sphinx==4.3.2,...
```

As far as I can tell Sphinx `v5` [still supports](https://github.com/sphinx-doc/sphinx/blob/0fd45397c1d5a252dca4d2be793e5a1bf189a74a/pyproject.toml#L16) Python 3.7, so I'm assuming there's something else in the test env is forcing an older version of Sphinx.

I've been able to reproduce this in a local `venv`, but I'm not sure 

- How to determine which package is holding the version of Sphinx back?
- How to override the dependency resolution to say "I really want this version"?

It's also interesting to note that the latest version of Sphinx `v4` is `4.5.0`

**Comment by stsewd** [comment]
Hi, I was able to track down this to flake8 https://github.com/swyddfa/esbonio/blob/26d972f529e3babbecc1e3a0a5b5b5c076ba8a81/lib/esbonio/setup.cfg#L56

flake8 and sphinx 5.x require incompatible versions of importlib-metadata

https://github.com/PyCQA/flake8/blob/6027577d325b0dd8bf1e465ebd29b71b5f0d005b/setup.cfg#L45

https://github.com/sphinx-doc/sphinx/blob/cbb19d6947d7d2a3898e2e0ca2c173071bca647b/pyproject.toml#L74

tox first install sphinx 5.x, but then when installing the `dev` extras it re-installs sphinx using a version that is compatible with flake8 (these installations are done in separate steps, that's why pip replaces it without given an error).

A solution could be not installing black or flake8, since they are managed by pre-commit, or maybe add another `extras_require` called `test` and just have the deps that are required to run the tests.

**Comment by alcarney** [comment]
Thanks for that! :) I assume you had to track that down by hand, rather than there being a tool/command that does it for you?

> or maybe add another `extras_require` called `test`

Good idea, it may even speed things up a little.

**Comment by stsewd** [comment]
>  I assume you had to track that down by hand, rather than there being a tool/command that does it for you?

Yeah, I ran tox in verbose mode `-vv` en checked the logs
