### ISSUE TITLE
Language server should be multi-root aware.

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#467]
While true support for multi-root workspaces will be challenging, the language server should at least be aware that they exist.

The most obvious scenario where this matters is when creating a sphinx application instance, when looking for `confDirs` etc. the server naively assumes there will only ever be one root and only checks the first one. It should at least check each root, if there's ambiguity, perhaps we can use  [`window/showMessageRequest`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest) and let the user decide which to use?

This should resolve issues seen in #326

**Comment by martinpakosch** [comment]
Hey @alcarney,

after confirming your debugging in #458 I did some more tests with multi-roots. And I can also confirm your assumption/description from above (using your debug logging):

1. With explicit paths set multi-roots work incl. preview as long as the folder with the sphinx project is defined at first among other roots in the workspace file (with lower-case `c:` drive-letter). So it has nothing to do with the location of the workspace file itself, what I assumed first.
2. With auto-path detection it is the same!

So for now it is even enough (for me) to put my sphinx folder to the top of my roots list. Fine as a workaround. 😁 Your fix in the LSP should not be that complicated though (scan multiple roots instead of one) - at least I hope so. But as a user I would highly appreciate your approach in terms of usability:

> It should at least check each root, if there's ambiguity, perhaps we can use [window/showMessageRequest](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest) and let the user decide which to use?

If that's to complicated, then simply inform the user to set explicit paths for the (single) specific sphinx project. But in doing so, you should not be far away from simply setting a list of paths to spin up multiple sphinx builds for multiple sphinx projects - at least when the user enables full multi-root support (by config?) because of the possible scaling issues (his problem, depending on his box). So, whatever you decide, it will be better than now. 😜

**Comment by alcarney** [comment]
Glad to hear you have a workaround :) 

> But in doing so, you should not be far away from simply setting a list of paths to spin up multiple sphinx builds for multiple sphinx projects

Unfortunately that's the easy step ;) Sphinx/docutils use a certain amount of global state, so standing up multiple sphinx projects will conflict with each other. Ideally the Sphinx builds should be offloaded into separate processes, technically possible, but the challenge will be getting all the info the server wants back out.
