### ISSUE TITLE
Manually closing backticks should not result in double backticks

### ISSUE THREAD

**Issue by neongreen-sc** [swyddfa/esbonio#895]
### Expected behavior

If I type `` :ref:`foo ``, for example, I should be able to press `` ` `` once more and get `` :ref:`foo` ``.

### Actual behavior

After typing the closing backtick I get ``` :ref:`foo`` ```.

### (Optional) Settings from conf.py

```python
(version: 0.95.1)
```

**Comment by alcarney** [comment]
I could be wrong, but I'm fairly sure this is due to the [language configuration](https://github.com/trond-snekvik/vscode-rst/blob/4371e09b22b145d159c4bf43e0e8916cc11bd193/rst-configuration.json#L18) for reStructuredText (which is now also [vendored](https://github.com/microsoft/vscode/blob/main/extensions/restructuredtext/language-configuration.json) in standard VSCode releases). So I'm not sure if this is something that can be fixed in Esbonio itself.

**Comment by neongreen-sc** [comment]
Oh, didn't know it was vendored. Closing then.

**Comment by neongreen-sc** [comment]
By the way -- upgraded to 0.95.1 and it's great that we have autocomplete for ref/doc now!

**Comment by alcarney** [comment]
Glad to hear it! It's taking a bit longer than I hoped, but the features from the stable release are starting to make their way over :)
